// Page copy shared by the React page AND the server (server/seo.ts renders it
// into the HTML so crawlers see real content). Edit text here, not in the page.
export const COPY = {
  ar: {
    badge: "الدفعة الثانية – أول شهادة مهنية متخصصة في الإدارة الثقافية في المملكة",
    programName: "ممارس الإدارة الثقافية",
    heroSub: "برنامج تأهيلي عملي لتطوير مهارات تصميم وإدارة المشاريع والمنظمات الثقافية.",
    bullets: ["7 مقررات معرفية وتطبيقية متكاملة", "مشروع تخرج بإشراف وتحكيم مهني", "لقاءات خبراء", "شهادة مهنية معتمدة"],
    apply: "قدّم طلبك الآن",
    guide: "تحميل الدليل التعريفي",
    whyH: "لماذا هذا البرنامج؟",
    quote: "القطاع الثقافي ينمو؛ فهل تنمو أدواتك معه؟",
    why1: "مع توسع المبادرات الثقافية في المملكة، تزداد الحاجة إلى كوادر قادرة على إدارة الثقافة باحترافية، وليس بالشغف وحده.",
    why2a: "صُمم برنامج ",
    why2b: "ممارس الإدارة الثقافية",
    why2c: " لسد الفجوة بين الإبداع والإدارة، وبين الفكرة والاستدامة.",
    whoH: "لمن هذا البرنامج؟",
    whoSub: "صُمم للممارسين الحقيقيين في القطاع الثقافي والفاعلين فيه.",
    audience: ["العاملين في الجهات الثقافية الحكومية والخاصة و غير الربحية", "مديري المبادرات والبرامج الثقافية", "المستقلين ومؤسسي المشاريع الثقافية", "المهتمين بتطوير مسار مهني احترافي في الثقافة"],
    learnH: "ماذا ستتعلم؟",
    learnSub: "7 مقررات معرفية وتطبيقية",
    courses: [
      { title: "مدخل إلى الإدارة الثقافية", description: "فهم المنظومة الثقافية، والحوكمة، والتخطيط الاستراتيجي." },
      { title: "اقتصاديات الثقافة", description: "نماذج التمويل، والاستدامة، والمؤشرات الاقتصادية." },
      { title: "علم النفس الثقافي", description: "سلوك الجمهور، وطرق التأثير، وبناء الحملات الثقافية المؤثرة." },
      { title: "إدارة المشاريع الثقافية", description: "من الفكرة إلى التنفيذ والتقييم." },
      { title: "تسويق وتمويل الثقافة", description: "بناء خطط تسويق وشراكات ورعايات مستدامة." },
      { title: "الوساطة الثقافية", description: "إدارة العلاقة بين المنتج الثقافي والجمهور." },
      { title: "إدارة المواهب الثقافية", description: "تصميم برامج اكتشاف وتنمية المواهب." },
    ],
    gradH: "مشروع التخرج",
    gradP: "يقوم المشارك بتقديم مشروع تخرج تطبيقي يوظف فيه معارفه ومهاراته التي اكتسبها من البرنامج.",
    toolsH: "أدوات البرنامج",
    toolsSub: "تجربة تعليمية تطبيقية متكاملة",
    tools: ["محاضرات تفاعلية وورش عمل", "قراءة متخصصة", "سماع موجه", "لقاءات خبراء", "دراسات حالة", "تدريب تطبيقي"],
    timeH: "الجدول الزمني للبرنامج",
    timeline: [
      { phase: "فتح التسجيل", date: "8 سبتمبر" },
      { phase: "إغلاق التسجيل", date: "22 سبتمبر" },
      { phase: "فرز الطلبات والمقابلات", date: "22 سبتمبر – 6 أكتوبر" },
      { phase: "استكمال السداد وتأكيد القبول", date: "7 – 12 أكتوبر" },
      { phase: "مرحلة المقررات", date: "أكتوبر – نوفمبر" },
      { phase: "مناقشة مشاريع التخرج", date: "12 ديسمبر" },
      { phase: "الحفل الختامي", date: "30 ديسمبر" },
    ],
    caption: "جدول مواد البرنامج والأساتذة ومواعيدها",
    thCourse: "المقرر",
    thInstructor: "الأستاذ",
    thDate: "التاريخ",
    fridaySat: "الجمعة والسبت",
    inPerson: "حضوريًا في الرياض",
    schedule: [
      { name: "مدخل إلى الإدارة الثقافية", instructor: "طارق الخواجي", date: "16-17 أكتوبر" },
      { name: "اقتصاديات الثقافة", instructor: "د. علي الحازمي", date: "23-24 أكتوبر" },
      { name: "الوساطة الثقافية", instructor: "عبد الرحمن لاهي", date: "30-31 أكتوبر" },
      { name: "إدارة المشاريع الثقافية", instructor: "عبدالكريم الخليفي", date: "6-7 نوفمبر" },
      { name: "تسويق وتمويل الثقافة", instructor: "تركي عبدالرحمن الخلف", date: "13-14 نوفمبر" },
      { name: "علم النفس الثقافي", instructor: "د. هيلة السليم", date: "20-21 نوفمبر" },
      { name: "إدارة المواهب الثقافية", instructor: "د. علا العلوان", date: "27-28 نوفمبر" },
    ],
    duration: "مدة البرنامج: أكتوبر – ديسمبر 2026",
    accH: "اعتماد البرنامج",
    accP: "البرنامج معتمد من منظمة بيرسون البريطانية، لضمان توافق البرنامج مع معايير الجودة العالمية في التعليم المهني، وتعزيز فرص الاعتراف الدولي بالشهادة.",
    badgeAlt: "شارة ممارس الإدارة الثقافية المعتمدة — Cultural Management Practitioner (CMPr)",
    partnersH: "شركاء البرنامج",
    strategic: "الشريك الاستراتيجي",
    aljaziraAlt: "بنك الجزيرة",
    ctaH: "قدّم طلبك الآن",
    ctaP: "سجّل الآن وانضم للدفعة الثانية من قادة الإدارة الثقافية",
    ctaBtn: "سجّل الآن",
    closed: "التسجيل مغلق",
    ctaClosedH: "اكتمل التسجيل",
    ctaClosedP: "أُغلق باب التسجيل في الدفعة الثانية، ترقّبوا الإعلان عن الدفعة القادمة",
  },
  en: {
    badge: "Second cohort – the first specialized professional certificate in cultural management in the Kingdom",
    programName: "Cultural Management Practitioner",
    heroSub: "A hands-on qualification program that builds the skills to design and manage cultural projects and organizations.",
    bullets: ["7 integrated knowledge and practical courses", "A graduation project with professional supervision and evaluation", "Expert meetings", "An accredited professional certificate"],
    apply: "Apply now",
    guide: "Download the program guide (Arabic)",
    whyH: "Why this program?",
    quote: "The cultural sector is growing — are your tools growing with it?",
    why1: "As cultural initiatives expand across the Kingdom, the need grows for professionals who can manage culture with expertise, not passion alone.",
    why2a: "The ",
    why2b: "Cultural Management Practitioner",
    why2c: " program was designed to bridge the gap between creativity and management, and between an idea and its sustainability.",
    whoH: "Who is this program for?",
    whoSub: "Designed for real practitioners in the cultural sector and those active in it.",
    audience: ["Professionals working in government, private and non-profit cultural organizations", "Managers of cultural initiatives and programs", "Freelancers and founders of cultural projects", "Anyone looking to build a professional career in culture"],
    learnH: "What will you learn?",
    learnSub: "7 knowledge and practical courses",
    courses: [
      { title: "Introduction to Cultural Management", description: "Understanding the cultural ecosystem, governance and strategic planning." },
      { title: "Economics of Culture", description: "Funding models, sustainability and economic indicators." },
      { title: "Cultural Psychology", description: "Audience behavior, methods of influence and building impactful cultural campaigns." },
      { title: "Cultural Project Management", description: "From idea to implementation and evaluation." },
      { title: "Marketing and Financing Culture", description: "Building sustainable marketing plans, partnerships and sponsorships." },
      { title: "Cultural Mediation", description: "Managing the relationship between the cultural product and the audience." },
      { title: "Cultural Talent Management", description: "Designing talent discovery and development programs." },
    ],
    gradH: "Graduation project",
    gradP: "Participants deliver an applied graduation project in which they put into practice the knowledge and skills gained from the program.",
    toolsH: "Program tools",
    toolsSub: "An integrated, applied learning experience",
    tools: ["Interactive lectures and workshops", "Specialized reading", "Guided listening", "Expert meetings", "Case studies", "Applied training"],
    timeH: "Program timeline",
    timeline: [
      { phase: "Registration opens", date: "8 September" },
      { phase: "Registration closes", date: "22 September" },
      { phase: "Application screening and interviews", date: "22 September – 6 October" },
      { phase: "Payment completion and confirmation of admission", date: "7 – 12 October" },
      { phase: "Courses phase", date: "October – November" },
      { phase: "Graduation project defense", date: "12 December" },
      { phase: "Closing ceremony", date: "30 December" },
    ],
    caption: "Table of program courses, instructors and dates",
    thCourse: "Course",
    thInstructor: "Instructor",
    thDate: "Date",
    fridaySat: "Friday and Saturday",
    inPerson: "In person in Riyadh",
    schedule: [
      { name: "Introduction to Cultural Management", instructor: "طارق الخواجي", date: "16–17 October" },
      { name: "Economics of Culture", instructor: "د. علي الحازمي", date: "23–24 October" },
      { name: "Cultural Mediation", instructor: "عبد الرحمن لاهي", date: "30–31 October" },
      { name: "Cultural Project Management", instructor: "عبدالكريم الخليفي", date: "6–7 November" },
      { name: "Marketing and Financing Culture", instructor: "تركي عبدالرحمن الخلف", date: "13–14 November" },
      { name: "Cultural Psychology", instructor: "د. هيلة السليم", date: "20–21 November" },
      { name: "Cultural Talent Management", instructor: "د. علا العلوان", date: "27–28 November" },
    ],
    duration: "Program duration: October – December 2026",
    accH: "Program accreditation",
    accP: "The program is accredited by the British organization Pearson, ensuring alignment with global quality standards in professional education and improving the chances of international recognition of the certificate.",
    badgeAlt: "Accredited Cultural Management Practitioner (CMPr) badge",
    partnersH: "Program partners",
    strategic: "Strategic partner",
    aljaziraAlt: "Bank AlJazira",
    ctaH: "Apply now",
    ctaP: "Register now and join the second cohort of cultural management leaders",
    ctaBtn: "Register now",
    closed: "Registration closed",
    ctaClosedH: "Registration is closed",
    ctaClosedP: "Registration for the second cohort has closed — stay tuned for the next cohort",
  },
};
