// Page copy shared by the React page AND the server (server/seo.ts renders it
// into the HTML so crawlers see real content). Edit text here, not in the page.
export const COPY = {
  ar: {
    pillars: { content: "المحتوى الثقافي", design: "التصميم الثقافي", education: "التعليم الثقافي" },
    badge: "المساهمة في بناء القدرات الثقافية",
    heading: "الخدمات",
    heroSub: "نرافق الجهات والأفراد العاملين في القطاع الثقافي عبر ثلاثة مسارات متكاملة: المحتوى، والتصميم، والتعليم.",
    cta: "اطلب الخدمة",
    serviceN: (n: string) => `الخدمة ${n}`,
    includes: "تشمل الخدمة:",
    pContent: "نُنتج محتوى معرفيًا متخصصًا يسهم في تطوير الممارسات المهنية في القطاع الثقافي، من خلال إعداد المقالات والدراسات والتقارير والأدلة والموارد المرجعية. وتركز الخدمة على نقل المعرفة، وتوثيق التجارب، وتحويل الخبرات والممارسات إلى محتوى مهني يدعم التعلم واتخاذ القرار وتطوير العمل الثقافي.",
    pDesign: "نساعد الجهات على تحويل الأفكار والطموحات الثقافية إلى برامج ومبادرات ومنتجات قابلة للتنفيذ والأثر. تشمل الخدمة تصميم البرامج الثقافية والفعاليات النوعية، وتطوير المبادرات والحلول الثقافية، وإعداد الأدلة المهنية والحقائب التدريبية، وبناء النماذج التشغيلية التي تضمن وضوح الرؤية وجودة التنفيذ واستدامة النتائج.",
    pEdu: "نعمل على تنمية القدرات المهنية للعاملين في القطاع الثقافي من خلال برامج تدريبية متخصصة وتجارب تعليمية تطبيقية تربط المعرفة بالممارسة. وتركز الخدمة على تأهيل الأفراد والفرق وتمكينهم من اكتساب المهارات والأدوات اللازمة لإدارة المشاريع والبرامج والمبادرات الثقافية بكفاءة واحترافية.",
    contentItems: ["إعداد الدراسات والتقارير المعرفية", "كتابة المقالات المتخصصة", "تطوير الأدلة والموارد المعرفية", "توثيق التجارب والممارسات الثقافية", "إنتاج النشرات والمحتوى المهني المتخصص"],
    designItems: ["تصميم البرامج والتجارب الثقافية", "تصميم المبادرات والحلول الثقافية", "تصميم الأدلة المهنية والإجرائية", "تصميم الحقائب التدريبية المتخصصة", "تطوير النماذج والأدوات التشغيلية"],
    educationItems: ["البرامج المهنية المتخصصة", "الدورات التدريبية", "ورش العمل التطبيقية", "برامج التأهيل والتطوير المهني", "اللقاءات والجلسات المعرفية المتخصصة"],
    formHeading: "نموذج طلب الخدمات",
    formIntro: "عرّفنا بطلبك وسيتواصل معك فريقنا لمناقشة التفاصيل والخطوات القادمة",
    sentTitle: "تم إرسال طلبك بنجاح!",
    sentBody: "شكراً لك، سنتواصل معك قريباً",
    name: "الاسم",
    namePlaceholder: "أدخل اسمك",
    email: "البريد الإلكتروني",
    emailPlaceholder: "أدخل بريدك الإلكتروني",
    phone: "رقم الجوال",
    organization: "اسم الجهة",
    organizationPlaceholder: "أدخل اسم جهتك",
    subject: "الموضوع",
    subjectPlaceholder: "اختر الخدمة المطلوبة",
    other: "أخرى",
    request: "الطلب",
    requestPlaceholder: "صف طلبك أو احتياجك بالتفصيل",
    sending: "جاري الإرسال...",
    submit: "إرسال الطلب",
    errorTitle: "خطأ",
    failed: "حدث خطأ أثناء إرسال البيانات",
    network: "حدث خطأ في الاتصال. يرجى المحاولة مرة أخرى.",
  },
  en: {
    pillars: { content: "Cultural Content", design: "Cultural Design", education: "Cultural Education" },
    badge: "Contributing to cultural capacity building",
    heading: "Services",
    heroSub: "We support organizations and individuals in the cultural sector through three integrated tracks: content, design and education.",
    cta: "Request a service",
    serviceN: (n: string) => `Service ${n}`,
    includes: "The service includes:",
    pContent: "We produce specialized knowledge content that helps develop professional practice in the cultural sector, through articles, studies, reports, guides and reference resources. The service focuses on transferring knowledge, documenting experiences, and turning expertise and practice into professional content that supports learning, decision-making and the development of cultural work.",
    pDesign: "We help organizations turn cultural ideas and ambitions into programs, initiatives and products that can be delivered and make an impact. The service covers designing cultural programs and distinctive events, developing cultural initiatives and solutions, preparing professional guides and training kits, and building operating models that ensure a clear vision, quality delivery and sustainable results.",
    pEdu: "We develop the professional capabilities of people working in the cultural sector through specialized training programs and applied learning experiences that connect knowledge with practice. The service focuses on qualifying individuals and teams and equipping them with the skills and tools needed to manage cultural projects, programs and initiatives efficiently and professionally.",
    contentItems: ["Preparing knowledge studies and reports", "Writing specialized articles", "Developing guides and knowledge resources", "Documenting cultural experiences and practices", "Producing newsletters and specialized professional content"],
    designItems: ["Designing cultural programs and experiences", "Designing cultural initiatives and solutions", "Designing professional and procedural guides", "Designing specialized training kits", "Developing operational templates and tools"],
    educationItems: ["Specialized professional programs", "Training courses", "Applied workshops", "Professional qualification and development programs", "Specialized knowledge meetups and sessions"],
    formHeading: "Service request form",
    formIntro: "Tell us about your request and our team will contact you to discuss the details and next steps",
    sentTitle: "Your request was sent successfully!",
    sentBody: "Thank you — we will be in touch soon",
    name: "Name",
    namePlaceholder: "Enter your name",
    email: "Email address",
    emailPlaceholder: "Enter your email address",
    phone: "Mobile number",
    organization: "Organization name",
    organizationPlaceholder: "Enter your organization's name",
    subject: "Subject",
    subjectPlaceholder: "Select the service you need",
    other: "Other",
    request: "Request",
    requestPlaceholder: "Describe your request or need in detail",
    sending: "Sending...",
    submit: "Submit request",
    errorTitle: "Error",
    failed: "Something went wrong while sending your details",
    network: "A connection error occurred. Please try again.",
  },
};
